[package]
name = "tt_fan_control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9.1"
byteorder = "1.3"
systemstat = "0.2.2"